server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mgmt_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "Password"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistence:
          validation:
            mode: none
  security:
    user:
      name: test
      password: test

logging:
  level:
    root: WARN
    com.aes.eventmanagementsystem: DEBUG
    org.hibernate.SQL: DEBUG